### ISSUE TITLE
Random outgroup 1

### ISSUE THREAD

**Issue by dr-chew** [EmiLithium/TWHAR#14]
Just a random outside writing sample (Nick Harkaway) that shouldn't has nothing to do with the op-ed, but would be alarming if it popped up as a false-positive.

**Comment by EmiLithium** [comment]
other outgroup ideas:
- thanks obama 
- the big p of the yew ess
- actually hitler

**Comment by EmiLithium** [comment]
@dr-chew, is NH1 finished?

**Comment by dr-chew** [comment]
I believe it had ~4K words, but I might be wrong.  Can check tonight.

**Comment by EmiLithium** [comment]
I think this is probably enough for outgroup 1, since the preliminary tests already showed really low matches anyway. Thanks @dr-chew !
